language: go
go: 
    - 1.5.1
    - release
before_install:
    - git clone git://github.com/jedisct1/libsodium.git
    - ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
    - git clone git://github.com/zeromq/libzmq.git
    - ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
install:
    - go get github.com/pebbe/zmq4
    - go get
script:
    - go test -v ./...
